name: "CI/CD"

on:
  push:
    branches:
      - feature/**

jobs:
  docker:
      name: Docker Build/Push
      runs-on: ubuntu-latest
      timeout-minutes: 20
      defaults:
        run:
          shell: bash

      steps:

      - name: checkout codebase
        uses: actions/checkout@v3

      - name: get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: declare variables for branch
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: variable values
        run: |
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"
          
      - name: list all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
