name: "CI/CD"

on:
  push:
    branches:
      - feature/**

jobs:
  python_package:
      name: Python Package for App deployment
      runs-on: ubuntu-latest
      timeout-minutes: 20
      defaults:
        run:
          shell: bash

      steps:


      - name: checkout codebase
        uses: actions/checkout@v3

      - name: get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: get changed files
        id: getfile
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for each_file in $changed_files;do
            if [[ "$each_file" == *"application"* ]]; then
              echo "$each_file"
            else
              exit 0
            fi
          done

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: generate tar file for app and upload
        id: generate_tar
        run: |
            tar_file=app_artifact_$(date +'%Y%m%d_%H%M').tar.gz
            tar -czvf "$tar_file" application/
            gsutil cp "$tar_file" gs://udb_app_artifacts/
        shell: bash
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}  # Provide GCP key file as a secret          

